### ISSUE TITLE
A little small demo?

### ISSUE THREAD

**Issue by frederikhors** [stephane-vanraes/renderless-svelte#15]
I can really appreciate your work as I have written the same components myself so far.

How about a demo, perhaps using a simple Bootstrap 5?

Just to give an idea of the component to those who come here for the first time.

**Comment by stephane-vanraes** [comment]
@frederikhors each component has a demo in the docs page already
or are you more looking for how to combine this with a framework like Bootstrap ? That could perhaps be added as a recipe

**Comment by frederikhors** [comment]
Yeah, I think it would be useful.

**Comment by stephane-vanraes** [comment]
I added a sample [here](https://renderless-svelte.dev/recipes/adding_bootstrap) but I am actually not entirely sure how to deal with this.  Bootstrap (or Tailwind, or whatever) are basically css frameworks, you would simply style your markup like any other markup using these frameworks.

Bootstrap is a bit tricker because some parts of it rely on using their javascript bundle as well (like in the modal example above).

It's also rather hard to embed the examples into the site itself because of styling conflicts :)

Not sure if this sample is what you are looking for ?
If I misunderstood the question let me know :)

**Comment by frederikhors** [comment]
Thank you.
